[package]
name = "telnet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
futures = "0.3.19"
async-std = "1.10.0"
tokio = "1.15.0"